### ISSUE TITLE
pyopengl < 3.1 is no longer supported in xpra 0.17.x

### ISSUE THREAD

**Issue by totaam** [urzds/xpra-docker#1]
You will no longer get accelerated opengl client rendering if you use a version that has not been updated in 4 years.
Version 3.1 does zero copy uploads.

**Comment by urzds** [comment]
The xpra repo contains `PyOpenGL-3.1.1a1r1-1.fc24.noarch`.

But thanks for the heads up, for `v0.17-pre12469-fedora-2` I switched to `python2-pyopengl`, the official Fedora 24 package.
